export const PILLARS = [
  {
    id: 1,
    title: "Identidade & Propósito",
    short: "Identidade",
    color: "bg-blue-900",
    textColor: "text-blue-900",
    lightBg: "bg-blue-50",
    borderColor: "border-blue-200",
    emoji: "🎯",
    checklist: [
      "Definiu sua especialidade principal e nicho de atuação",
      "Criou sua declaração de propósito profissional",
      "Identificou seus 3 principais diferenciais competitivos",
      "Mapeou os valores inegociáveis da sua prática médica",
      "Definiu o perfil ideal do seu paciente",
      "Elaborou sua história profissional (storytelling)",
      "Revisou e atualizou seu currículo e bio profissional",
    ],
  },
  {
    id: 2,
    title: "Posicionamento Premium",
    short: "Posicionamento",
    color: "bg-indigo-900",
    textColor: "text-indigo-900",
    lightBg: "bg-indigo-50",
    borderColor: "border-indigo-200",
    emoji: "⭐",
    checklist: [
      "Analisou os principais concorrentes da sua região",
      "Definiu seu posicionamento único de mercado",
      "Criou ou revisou sua identidade visual (logo, cores, fontes)",
      "Desenvolveu sua proposta de valor clara e diferenciada",
      "Estabeleceu sua política de preços premium",
      "Criou materiais de apresentação profissional",
      "Definiu os canais de comunicação prioritários",
    ],
  },
  {
    id: 3,
    title: "Diagnóstico do Negócio",
    short: "Diagnóstico",
    color: "bg-slate-800",
    textColor: "text-slate-800",
    lightBg: "bg-slate-50",
    borderColor: "border-slate-200",
    emoji: "📊",
    checklist: [
      "Preencheu o questionário iVMP completo",
      "Mapeou todas as despesas fixas e variáveis",
      "Calculou o custo real por hora de atendimento",
      "Analisou a taxa de ocupação da agenda",
      "Identificou os 3 principais gargalos operacionais",
      "Calculou o ponto de equilíbrio financeiro",
      "Definiu metas financeiras para os próximos 12 meses",
    ],
  },
  {
    id: 4,
    title: "Estrutura Operacional",
    short: "Operacional",
    color: "bg-blue-800",
    textColor: "text-blue-800",
    lightBg: "bg-blue-50",
    borderColor: "border-blue-200",
    emoji: "⚙️",
    checklist: [
      "Mapeou todos os processos críticos da clínica",
      "Criou manual de processos para a equipe",
      "Definiu indicadores de desempenho (KPIs) por função",
      "Implementou sistema de gestão e prontuário eletrônico",
      "Criou programa de treinamento para a equipe",
      "Estabeleceu rotinas de reunião e feedback",
      "Delegou responsabilidades com clareza",
    ],
  },
  {
    id: 5,
    title: "Precificação & Financeiro",
    short: "Financeiro",
    color: "bg-amber-800",
    textColor: "text-amber-800",
    lightBg: "bg-amber-50",
    borderColor: "border-amber-200",
    emoji: "💰",
    checklist: [
      "Calculou o preço mínimo de cada procedimento",
      "Definiu a tabela de preços com margem adequada",
      "Separou as finanças pessoais das da clínica",
      "Criou controle de fluxo de caixa mensal",
      "Estabeleceu reserva de emergência (3 meses)",
      "Definiu pró-labore adequado",
      "Criou plano de investimentos para os próximos 12 meses",
    ],
  },
  {
    id: 6,
    title: "Marketing & Digital",
    short: "Marketing",
    color: "bg-teal-800",
    textColor: "text-teal-800",
    lightBg: "bg-teal-50",
    borderColor: "border-teal-200",
    emoji: "📱",
    checklist: [
      "Criou ou otimizou perfil no Instagram/LinkedIn",
      "Definiu calendário editorial mensal",
      "Produziu 10 conteúdos educativos para redes sociais",
      "Criou ou atualizou site profissional",
      "Configurou Google Meu Negócio",
      "Implementou estratégia de captação de indicações",
      "Criou sequência de e-mail marketing para novos pacientes",
    ],
  },
  {
    id: 7,
    title: "Vendas & Valor Percebido",
    short: "Vendas",
    color: "bg-rose-900",
    textColor: "text-rose-900",
    lightBg: "bg-rose-50",
    borderColor: "border-rose-200",
    emoji: "🤝",
    checklist: [
      "Aprendeu a apresentar tratamentos com valor percebido",
      "Criou script de apresentação de planos de tratamento",
      "Treinou a equipe em técnicas de conversão ética",
      "Implementou sistema de follow-up pós-consulta",
      "Criou materiais de apoio para apresentação de tratamentos",
      "Definiu política de parcelamento e formas de pagamento",
      "Mediu e melhorou taxa de adesão a tratamentos",
    ],
  },
];

export const PILLAR_COLORS = [
  { bg: "bg-blue-900", text: "text-white", light: "bg-blue-50", border: "border-blue-200" },
  { bg: "bg-indigo-900", text: "text-white", light: "bg-indigo-50", border: "border-indigo-200" },
  { bg: "bg-slate-800", text: "text-white", light: "bg-slate-50", border: "border-slate-200" },
  { bg: "bg-blue-800", text: "text-white", light: "bg-blue-50", border: "border-blue-200" },
  { bg: "bg-amber-800", text: "text-white", light: "bg-amber-50", border: "border-amber-200" },
  { bg: "bg-teal-800", text: "text-white", light: "bg-teal-50", border: "border-teal-200" },
  { bg: "bg-rose-900", text: "text-white", light: "bg-rose-50", border: "border-rose-200" },
];
