/**
 * Perguntas por Pilar — Questionário Autônomo do Mentorado
 *
 * Cada pilar tem seções temáticas com perguntas guiadas.
 * Linguagem simples, sem jargões técnicos.
 * Todas as perguntas têm opção "Não sei".
 */
import type { Section } from "@/components/MenteePillarQuestionnaire";

// ============================================================
// PILAR 1 — IDENTIDADE E PROPÓSITO
// ============================================================
export const pillar1Sections: Section[] = [
  {
    id: "quem_sou",
    titulo: "Quem sou eu",
    descricao: "Vamos começar pelo mais importante: você. Responda com sinceridade — não há resposta certa ou errada.",
    icone: "🪞",
    perguntas: [
      {
        id: "p1_nome_completo",
        pergunta: "Qual é o seu nome completo e sua especialidade médica?",
        tipo: "text",
        placeholder: "Ex: Dr. João Silva — Cardiologista",
        obrigatoria: true,
      },
      {
        id: "p1_tempo_formado",
        pergunta: "Há quantos anos você é médico?",
        tipo: "number",
        placeholder: "Ex: 12",
        unidade: "anos",
        guia: "Conte a partir da data de formatura, não da residência.",
      },
      {
        id: "p1_por_que_medicina",
        pergunta: "Por que você escolheu ser médico? O que te motivou a seguir essa carreira?",
        tipo: "textarea",
        placeholder: "Escreva livremente. Pode ser uma história, uma pessoa, um momento...",
        guia: "Não precisa ser uma resposta elaborada. Pode ser algo simples como 'queria ajudar pessoas' ou uma história pessoal.",
        exemplo: "Minha avó ficou doente quando eu tinha 10 anos e vi o médico dela fazer uma diferença enorme na vida dela. Quis ser aquela pessoa para outras famílias.",
      },
      {
        id: "p1_orgulho",
        pergunta: "Qual conquista da sua carreira médica te dá mais orgulho até hoje?",
        tipo: "textarea",
        placeholder: "Pode ser um caso clínico, um reconhecimento, uma mudança que você fez...",
        guia: "Pense em momentos em que você sentiu que fez a diferença — seja para um paciente, para sua equipe ou para sua especialidade.",
      },
      {
        id: "p1_diferente",
        pergunta: "O que você faz de diferente dos outros médicos da sua especialidade?",
        tipo: "textarea",
        placeholder: "Pense no seu jeito de atender, de explicar, de cuidar...",
        guia: "Não precisa ser algo revolucionário. Pode ser o tempo que você dedica ao paciente, a forma como explica o diagnóstico, ou uma técnica específica que você domina.",
      },
    ],
  },
  {
    id: "valores",
    titulo: "Seus valores",
    descricao: "Os valores são os princípios que guiam suas decisões — na medicina e na vida.",
    icone: "⭐",
    perguntas: [
      {
        id: "p1_valores",
        pergunta: "Quais são os 3 valores mais importantes para você como médico?",
        tipo: "multiselect",
        opcoes: [
          "Honestidade", "Empatia", "Excelência técnica", "Humanização",
          "Inovação", "Ética", "Comprometimento", "Equilíbrio",
          "Família", "Liberdade", "Impacto social", "Prosperidade",
        ],
        guia: "Escolha os que realmente guiam suas decisões no dia a dia, não os que 'deveriam' guiar.",
      },
      {
        id: "p1_valor_principal_significado",
        pergunta: "Do valor que você mais se identifica, o que ele significa na prática para você?",
        tipo: "textarea",
        placeholder: "Como esse valor aparece no seu atendimento, nas suas decisões, na sua rotina?",
        guia: "Por exemplo: se escolheu 'Empatia', como ela aparece no seu dia a dia com os pacientes?",
      },
      {
        id: "p1_nao_abre_mao",
        pergunta: "O que você nunca abriria mão na sua prática médica, mesmo sob pressão?",
        tipo: "textarea",
        placeholder: "Ex: Nunca abriria mão de explicar o diagnóstico com calma para o paciente...",
      },
    ],
  },
  {
    id: "missao_visao",
    titulo: "Propósito e Visão de Futuro",
    descricao: "Estas perguntas ajudam o mentor a entender para onde você quer ir. Responda com sinceridade sobre seus sonhos e objetivos.",
    icone: "🎯",
    perguntas: [
      {
        id: "p1_quem_ajuda",
        pergunta: "Quem são as pessoas que você mais quer ajudar com a sua medicina?",
        tipo: "textarea",
        placeholder: "Ex: Mulheres acima de 40 anos com problemas hormonais, executivos com alto estresse...",
        guia: "Pense no perfil do paciente com quem você se sente mais realizado atendendo.",
        obrigatoria: true,
      },
      {
        id: "p1_problema_resolve",
        pergunta: "Qual problema principal você resolve na vida dessas pessoas?",
        tipo: "textarea",
        placeholder: "Ex: Ajudo a recuperar a qualidade de vida, a ter energia de volta, a dormir bem...",
        guia: "Pense além do diagnóstico clínico — qual é o impacto real na vida do paciente?",
      },
      {
        id: "p1_como_resolve",
        pergunta: "Como você resolve esse problema? O que torna seu tratamento especial?",
        tipo: "textarea",
        placeholder: "Ex: Através de um acompanhamento próximo, com medicina integrativa, com protocolos personalizados...",
      },
      {
        id: "p1_visao_5anos",
        pergunta: "Como você se imagina daqui a 5 anos? O que você quer ter conquistado?",
        tipo: "textarea",
        placeholder: "Pense na sua clínica, na sua equipe, nos seus pacientes, na sua vida pessoal...",
        guia: "Seja específico. Não precisa ser realista agora — seja honesto sobre o que realmente deseja.",
        exemplo: "Quero ter uma clínica com 3 médicos, atender 15 pacientes por dia (não mais), ter tempo para viajar 2 vezes por ano e ganhar R$ 50.000/mês.",
      },
      {
        id: "p1_legado",
        pergunta: "Que legado você quer deixar como médico? Como quer ser lembrado pelos seus pacientes e pela sua especialidade?",
        tipo: "textarea",
        placeholder: "Ex: Quero ser lembrado como o médico que realmente ouvia seus pacientes...",
      },
    ],
  },
  {
    id: "ikigai",
    titulo: "Ikigai — Seu Propósito",
    descricao: "O Ikigai é a intersecção entre o que você ama, o que você faz bem, o que o mundo precisa e pelo que você pode ser pago. Responda cada dimensão com honestidade.",
    icone: "🧭",
    perguntas: [
      {
        id: "p1_ikigai_ama",
        pergunta: "O que você AMA na medicina? Quais atividades, casos ou momentos te dão energia e prazer genuíno?",
        tipo: "textarea",
        placeholder: "Ex: Procedimentos de alta complexidade que exigem raciocínio clínico apurado; acompanhar pacientes crônicos ao longo do tempo; ensinar residentes...",
        guia: "Pense: qual tipo de caso faz você esquecer o tempo enquanto trabalha? O que você faria mesmo sem ser pago?",
        obrigatoria: true,
      },
      {
        id: "p1_ikigai_bom",
        pergunta: "No que você é BOM? Quais são suas habilidades técnicas, competências únicas e diferenciais que colegas reconhecem?",
        tipo: "textarea",
        placeholder: "Ex: Diagnóstico diferencial em casos complexos; procedimentos minimamente invasivos; comunicação empática com pacientes difíceis...",
        guia: "O que você faz que nenhum colega da sua especialidade faz igual? Para que tipo de caso os colegas te pedem opinião?",
        obrigatoria: true,
      },
      {
        id: "p1_ikigai_mundo",
        pergunta: "O que o mundo PRECISA que você oferece? Quais lacunas reais você preenche no mercado médico?",
        tipo: "textarea",
        placeholder: "Ex: Pacientes com dor crônica sem diagnóstico preciso; falta de abordagem integrativa; ausência de especialista em determinada área na região...",
        guia: "Qual problema de saúde na sua região é mal tratado? Que queixa você ouve repetidamente de pacientes que não encontram solução?",
        obrigatoria: true,
      },
      {
        id: "p1_ikigai_pago",
        pergunta: "Pelo que você pode ser PAGO? Quais serviços têm demanda real e disposição de pagamento no seu mercado?",
        tipo: "textarea",
        placeholder: "Ex: Consultas de segunda opinião para casos complexos; medicina preventiva e longevidade; tratamentos não cobertos por planos...",
        guia: "Qual serviço seus pacientes pagariam mais sem questionar o preço? Qual procedimento tem maior demanda reprimida na sua área?",
        obrigatoria: true,
      },
      {
        id: "p1_ikigai_proposta",
        pergunta: "Se você tivesse que resumir em uma frase o que te move como médico, o que diria?",
        tipo: "textarea",
        placeholder: "Escreva livremente — seu mentor usará essa resposta junto com as anteriores para construir seu Ikigai completo.",
        guia: "Não precisa ser perfeita. É uma reflexão inicial que o mentor vai aprofundar com você.",
      },
    ],
  },
  {
    id: "valores_avancados",
    titulo: "Seus Valores Inegociáveis",
    descricao: "Os valores são os princípios que guiam suas decisões mais difíceis. Vamos identificar os que realmente te movem.",
    icone: "⭐",
    perguntas: [
      {
        id: "p1_valores_catalogo",
        pergunta: "Selecione até 5 valores que mais representam quem você é como médico:",
        tipo: "multiselect",
        opcoes: [
          "Excelência clínica", "Empatia genuína", "Honestidade radical",
          "Inovação contínua", "Autonomia do paciente", "Educação em saúde",
          "Integridade científica", "Presença total", "Resultados concretos",
          "Cuidado integral", "Liberdade terapêutica", "Responsabilidade",
          "Curiosidade intelectual", "Impacto social", "Equilíbrio vida-trabalho",
          "Colaboração",
        ],
        guia: "Escolha os que realmente guiam suas decisões no dia a dia, não os que 'deveriam' guiar.",
        obrigatoria: true,
      },
      {
        id: "p1_valor_principal_manifestacao",
        pergunta: "Do valor que você mais se identifica, como ele aparece concretamente no seu atendimento?",
        tipo: "textarea",
        placeholder: "Ex: Se escolheu 'Empatia genuína': sempre reservo 5 minutos no final da consulta para o paciente falar sobre como está se sentindo emocionalmente...",
        guia: "Seja específico. Valores que não se manifestam em ações concretas são apenas intenções.",
      },
      {
        id: "p1_valor_conflito",
        pergunta: "Já teve alguma situação em que precisou defender um valor seu contra pressão externa (plano de saúde, chefia, colegas)? O que aconteceu?",
        tipo: "textarea",
        placeholder: "Ex: Recusei prescrever um medicamento que o plano exigia porque não era o melhor para o paciente...",
        guia: "Valores verdadeiros são testados sob pressão. Esta pergunta ajuda a identificar o que é inegociável para você.",
      },
    ],
  },

  {
    id: "reflexao_identidade",
    titulo: "Reflexão Final — Aprofundamento",
    descricao: "Estas perguntas finais nos ajudam a construir sua identidade profissional completa. Responda com calma e sinceridade.",
    icone: "✨",
    perguntas: [
      {
        id: "p1_flow_momento",
        pergunta: "Descreva um momento recente em que você estava tão absorto no trabalho que perdeu a noção do tempo. O que estava fazendo?",
        tipo: "textarea",
        placeholder: "Ex: Estava operando um caso complexo e quando percebi já eram 3 horas depois...",
        guia: "Esses momentos de 'flow' revelam onde está seu maior talento e paixão genuína.",
      },
      {
        id: "p1_reconhecimento_externo",
        pergunta: "Para que tipo de caso ou situação seus colegas médicos te ligam pedindo opinião ou encaminhando pacientes?",
        tipo: "textarea",
        placeholder: "Ex: Colegas me ligam quando têm casos de dor crônica sem diagnóstico definido...",
        guia: "O reconhecimento dos colegas é um indicador poderoso do seu diferencial real.",
      },
      {
        id: "p1_impacto_orgulha",
        pergunta: "Qual impacto que você causou na vida de um paciente te deu mais orgulho? Descreva brevemente.",
        tipo: "textarea",
        placeholder: "Ex: Uma paciente que não conseguia trabalhar por dor voltou a correr maratona após meu tratamento...",
        guia: "Este impacto revela o que você realmente entrega além do tratamento clínico.",
      },
      {
        id: "p1_nao_faria_nunca",
        pergunta: "Que tipo de atendimento, paciente ou situação você recusaria mesmo que pagassem muito bem?",
        tipo: "textarea",
        placeholder: "Ex: Nunca faria procedimentos estéticos sem indicação clínica real, mesmo que o paciente insistisse...",
        guia: "O que você recusa define seus valores tão claramente quanto o que você aceita.",
      },
      {
        id: "p1_transformacao_paciente",
        pergunta: "Em uma frase, qual é a transformação concreta que um paciente vive depois de ser tratado por você?",
        tipo: "textarea",
        placeholder: "Ex: Meus pacientes passam de 'vivendo com a dor' para 'voltando a viver com qualidade'...",
        guia: "Pense no 'antes e depois' mais poderoso que você já proporcionou.",
        obrigatoria: true,
      },
      {
        id: "p1_mensagem_medico_jovem",
        pergunta: "Se você pudesse dar um conselho para um médico recém-formado que quer seguir o mesmo caminho que você, o que diria?",
        tipo: "textarea",
        placeholder: "Ex: Escolha uma área que te dê energia, não apenas prestígio. Construa relações antes de construir uma marca...",
        guia: "Sua resposta revela seus valores mais profundos e o que você aprendeu na prática.",
      },
    ],
  },
];


// ============================================================
// PILAR 2 — POSICIONAMENTO
// ============================================================
export const pillar2Sections: Section[] = [
  {
    id: "especialidade_atuacao",
    titulo: "Sua especialidade e atuação",
    descricao: "Vamos entender melhor como você atua hoje e onde você se destaca.",
    icone: "🏥",
    perguntas: [
      {
        id: "p2_especialidade",
        pergunta: "Qual é a sua especialidade médica principal?",
        tipo: "text",
        placeholder: "Ex: Cardiologia, Dermatologia, Ortopedia...",
        obrigatoria: true,
      },
      {
        id: "p2_subespecialidade",
        pergunta: "Você tem alguma subespecialidade ou área de foco dentro da sua especialidade?",
        tipo: "text",
        placeholder: "Ex: Cardiologia preventiva, Dermatologia estética, Ortopedia do joelho...",
        guia: "Subespecialidade é quando você se aprofundou em uma área específica dentro da sua especialidade principal.",
      },
      {
        id: "p2_procedimentos_principais",
        pergunta: "Quais são os 3 procedimentos ou tratamentos que você mais realiza?",
        tipo: "textarea",
        placeholder: "Liste os procedimentos que ocupam a maior parte do seu tempo clínico",
        obrigatoria: true,
      },
      {
        id: "p2_procedimento_favorito",
        pergunta: "Qual procedimento ou tipo de atendimento você mais gosta de fazer?",
        tipo: "textarea",
        placeholder: "O que te dá mais satisfação no trabalho?",
        guia: "Pense no que faz o tempo passar rápido, no que você faz com mais entusiasmo.",
      },
      {
        id: "p2_onde_atende",
        pergunta: "Onde você atende? (pode marcar mais de um)",
        tipo: "multiselect",
        opcoes: [
          "Consultório próprio", "Clínica compartilhada", "Hospital",
          "Home care (domiciliar)", "Telemedicina", "Outro",
        ],
        obrigatoria: true,
      },
      {
        id: "p2_cidade",
        pergunta: "Em qual cidade e estado você atende principalmente?",
        tipo: "text",
        placeholder: "Ex: São Paulo - SP",
        obrigatoria: true,
      },
    ],
  },
  {
    id: "publico_ideal",
    titulo: "Seu paciente ideal",
    descricao: "Entender quem é seu paciente ideal é fundamental para um posicionamento forte.",
    icone: "👤",
    perguntas: [
      {
        id: "p2_paciente_ideal_descricao",
        pergunta: "Como você descreveria o seu paciente ideal? (idade, perfil, situação de vida)",
        tipo: "textarea",
        placeholder: "Ex: Mulheres entre 35 e 55 anos, profissionais liberais, que se preocupam com saúde preventiva...",
        guia: "Pense no paciente com quem você tem mais afinidade e obtém melhores resultados.",
        obrigatoria: true,
      },
      {
        id: "p2_paciente_dor_principal",
        pergunta: "Qual é a principal dor ou problema que esse paciente ideal traz para você?",
        tipo: "textarea",
        placeholder: "Ex: Cansaço crônico, dores no joelho que impedem de se exercitar, ansiedade...",
        guia: "Pense além do diagnóstico — qual é o impacto desse problema na vida do paciente?",
      },
      {
        id: "p2_paciente_sonho",
        pergunta: "Qual é o maior sonho ou desejo do seu paciente ideal relacionado à saúde?",
        tipo: "textarea",
        placeholder: "Ex: Voltar a jogar futebol com os filhos, emagrecer 15kg, dormir bem de novo...",
      },
      {
        id: "p2_poder_aquisitivo",
        pergunta: "Qual é o perfil econômico do seu paciente ideal?",
        tipo: "select",
        opcoes: [
          "Classe C (renda familiar R$ 2.000-8.000)",
          "Classe B (renda familiar R$ 8.000-20.000)",
          "Classe A (renda familiar acima de R$ 20.000)",
          "Misto — atendo todos os perfis",
        ],
        guia: "Isso influencia diretamente na precificação e na comunicação do seu serviço.",
      },
      {
        id: "p2_plano_saude",
        pergunta: "Você atende por plano de saúde, particular ou os dois?",
        tipo: "select",
        opcoes: [
          "Somente plano de saúde",
          "Somente particular",
          "Plano de saúde e particular",
          "Plano de saúde, particular e convênios corporativos",
        ],
        obrigatoria: true,
      },
    ],
  },
  {
    id: "diferencial",
    titulo: "Seu diferencial",
    descricao: "O diferencial é o que faz um paciente te escolher em vez de outro médico da mesma especialidade.",
    icone: "💎",
    perguntas: [
      {
        id: "p2_por_que_escolhem",
        pergunta: "Por que os pacientes te escolhem? O que eles costumam falar sobre você?",
        tipo: "textarea",
        placeholder: "Pense nos elogios que você recebe, nos comentários que os pacientes fazem...",
        guia: "Se não souber, pense no que seus pacientes mais fiéis costumam dizer. Ou pergunte a eles!",
        obrigatoria: true,
      },
      {
        id: "p2_diferencial_tecnico",
        pergunta: "Você tem alguma formação, técnica ou tecnologia que poucos médicos da sua cidade têm?",
        tipo: "textarea",
        placeholder: "Ex: Pós-graduação em medicina integrativa, equipamento de última geração, técnica cirúrgica específica...",
        guia: "Isso pode ser um curso, uma certificação, um equipamento, ou uma abordagem de tratamento diferente.",
      },
      {
        id: "p2_diferencial_atendimento",
        pergunta: "Como é o seu atendimento? O que o torna diferente?",
        tipo: "textarea",
        placeholder: "Ex: Consultas de 1 hora, acompanhamento por WhatsApp, retorno em 24h, equipe multidisciplinar...",
      },
      {
        id: "p2_concorrentes",
        pergunta: "Você conhece outros médicos da sua especialidade na sua cidade? O que te diferencia deles?",
        tipo: "textarea",
        placeholder: "Não precisa citar nomes. Fale sobre o que você faz diferente.",
        guia: "Se não souber, tudo bem — marque 'Não sei'. Isso é algo que trabalharemos juntos.",
      },
    ],
  },
  {
    id: "proposta_valor",
    titulo: "Proposta de Valor — Aprofundamento",
    descricao: "Estas perguntas finais nos ajudam a construir sua proposta de valor e posicionamento de nicho.",
    icone: "✨",
    perguntas: [
      {
        id: "p2_o_que_paciente_conta",
        pergunta: "O que um paciente satisfeito conta para um amigo sobre você? Qual é a frase que ele usa?",
        tipo: "textarea",
        placeholder: "Ex: 'Ele é o único médico que realmente me ouviu e encontrou o problema que ninguém achava'...",
        guia: "Essa é sua proposta de valor real — o que seus melhores pacientes dizem espontaneamente.",
        obrigatoria: true,
      },
      {
        id: "p2_nicho_sonho",
        pergunta: "Se você pudesse atender apenas um tipo específico de paciente pelo resto da sua carreira, quem seria?",
        tipo: "textarea",
        placeholder: "Ex: Executivos acima de 50 anos que querem longevidade com qualidade de vida...",
        guia: "Sem julgamento — qual é o paciente com quem você se sente mais realizado e obtém melhores resultados?",
        obrigatoria: true,
      },
      {
        id: "p2_resultado_garantido",
        pergunta: "Para qual tipo de problema ou paciente você tem mais confiança de entregar um resultado excelente?",
        tipo: "textarea",
        placeholder: "Ex: Pacientes com dor crônica de coluna que já tentaram outros tratamentos sem sucesso...",
        guia: "Onde você tem o maior histórico de sucesso? Para qual caso você diria 'confie em mim, vou resolver'?",
      },
      {
        id: "p2_mercado_nao_atendido",
        pergunta: "Existe algum grupo de pacientes na sua cidade que não está sendo bem atendido pela sua especialidade?",
        tipo: "textarea",
        placeholder: "Ex: Idosos com múltiplas comorbidades que precisam de um especialista que coordene todos os tratamentos...",
        guia: "Lacunas de mercado são oportunidades de posicionamento. O que você vê que outros não estão fazendo?",
      },
      {
        id: "p2_proposta_frase",
        pergunta: "Em uma frase, complete: 'Eu ajudo [quem] a [resultado] através de [como].'",
        tipo: "textarea",
        placeholder: "Ex: Eu ajudo executivos acima de 50 anos a recuperar energia e longevidade através de medicina preventiva personalizada.",
        guia: "Esta é a base da sua proposta de valor. Não precisa ser perfeita — o mentor vai refiná-la com você.",
        obrigatoria: true,
      },
    ],
  },
];

// ============================================================
// PILAR 3 — DIAGNÓSTICO DO NEGÓCIO (CUSTOS E FINANÇAS)
// ============================================================
export const pillar3Sections: Section[] = [
  {
    id: "estrutura_clinica",
    titulo: "Sua clínica e estrutura",
    descricao: "Vamos entender como está estruturado o seu consultório ou clínica hoje.",
    icone: "🏢",
    perguntas: [
      {
        id: "p3_tipo_local",
        pergunta: "Como é o seu local de atendimento?",
        tipo: "select",
        opcoes: [
          "Consultório próprio (imóvel meu)",
          "Consultório alugado (pago aluguel)",
          "Sala em clínica compartilhada (pago por hora ou por dia)",
          "Atendo em hospital (sem custo de sala)",
          "Atendo em casa (home office)",
          "Mais de um local",
        ],
        obrigatoria: true,
      },
      {
        id: "p3_aluguel_valor",
        pergunta: "Quanto você paga de aluguel ou locação do espaço por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Se paga por hora ou por dia, calcule o valor médio mensal. Se o imóvel é próprio, coloque 0.",
        dependeDe: { id: "p3_tipo_local", valor: "Consultório alugado (pago aluguel)" },
      },
      {
        id: "p3_aluguel_valor_geral",
        pergunta: "Quanto você gasta mensalmente com o espaço de atendimento? (aluguel, locação por hora, taxa de uso da clínica, etc.)",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Some todos os custos relacionados ao espaço físico onde você atende.",
      },
      {
        id: "p3_tem_equipe",
        pergunta: "Você tem funcionários ou colaboradores?",
        tipo: "yesno",
        obrigatoria: true,
      },
      {
        id: "p3_equipe_quantidade",
        pergunta: "Quantas pessoas trabalham com você?",
        tipo: "number",
        placeholder: "Ex: 2",
        guia: "Conte secretária, recepcionista, auxiliar, enfermeiro, médico sócio, etc.",
        dependeDe: { id: "p3_tem_equipe", valor: "Sim" },
      },
      {
        id: "p3_equipe_funcoes",
        pergunta: "Quais são as funções das pessoas que trabalham com você?",
        tipo: "textarea",
        placeholder: "Ex: 1 secretária, 1 auxiliar de enfermagem, 1 médico sócio...",
        dependeDe: { id: "p3_tem_equipe", valor: "Sim" },
      },
    ],
  },
  {
    id: "custos_fixos",
    titulo: "Custos fixos mensais",
    descricao: "Estes são os gastos que você tem todo mês, independente de quantos pacientes atender. Seja o mais preciso possível — use extratos bancários se precisar.",
    icone: "💸",
    perguntas: [
      {
        id: "p3_custo_pessoal",
        pergunta: "Quanto você gasta com salários e encargos de funcionários por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: salário bruto + INSS patronal (20%) + FGTS (8%) + férias proporcionais + 13º proporcional. Se não souber calcular, coloque o valor dos salários e marque 'Não sei' para os encargos.",
        exemplo: "Se paga R$ 2.000 de salário, o custo real é aproximadamente R$ 2.800 com encargos.",
      },
      {
        id: "p3_custo_contador",
        pergunta: "Quanto você paga de contador ou escritório contábil por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua honorários do contador e qualquer taxa de abertura/manutenção de empresa.",
      },
      {
        id: "p3_custo_energia",
        pergunta: "Quanto você gasta com energia elétrica do consultório por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Se o consultório é em casa, estime a proporção usada para o trabalho.",
      },
      {
        id: "p3_custo_agua",
        pergunta: "Quanto você gasta com água do consultório por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
      },
      {
        id: "p3_custo_internet",
        pergunta: "Quanto você gasta com internet e telefone do consultório por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua internet fixa, telefone fixo e o plano de celular que você usa para trabalho.",
      },
      {
        id: "p3_custo_materiais",
        pergunta: "Quanto você gasta com materiais médicos e insumos por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: luvas, máscaras, seringas, medicamentos de emergência, materiais de procedimento, etc.",
        exemplo: "Luvas R$ 80 + máscaras R$ 40 + seringas R$ 30 = R$ 150/mês",
      },
      {
        id: "p3_custo_limpeza",
        pergunta: "Quanto você gasta com limpeza e higienização do consultório por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: produtos de limpeza, serviço de limpeza terceirizado, esterilização de materiais.",
      },
      {
        id: "p3_custo_software",
        pergunta: "Quanto você gasta com sistemas e softwares por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: prontuário eletrônico, agendamento online, WhatsApp Business, Google Workspace, etc.",
        exemplo: "Prontuário R$ 150 + agendamento R$ 50 = R$ 200/mês",
      },
      {
        id: "p3_custo_marketing",
        pergunta: "Quanto você gasta com marketing e publicidade por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: anúncios no Instagram/Google, designer, fotógrafo, site, etc.",
      },
      {
        id: "p3_custo_seguros",
        pergunta: "Quanto você gasta com seguros por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: seguro de responsabilidade civil médica (SRMM), seguro do consultório, etc.",
      },
      {
        id: "p3_custo_associacoes",
        pergunta: "Quanto você gasta com anuidades de conselhos e associações por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: CRM, CFM, sociedades médicas da sua especialidade. Divida o valor anual por 12.",
        exemplo: "CRM R$ 600/ano ÷ 12 = R$ 50/mês",
      },
    ],
  },
  {
    id: "custos_deslocamento",
    titulo: "Custos de deslocamento",
    descricao: "Muitos médicos esquecem de calcular o custo do deslocamento. Vamos incluir tudo.",
    icone: "🚗",
    perguntas: [
      {
        id: "p3_se_desloca",
        pergunta: "Você precisa se deslocar para trabalhar? (ir ao consultório, hospital, outra cidade)",
        tipo: "yesno",
        obrigatoria: true,
      },
      {
        id: "p3_tipo_deslocamento",
        pergunta: "Como você se desloca para trabalhar?",
        tipo: "multiselect",
        opcoes: [
          "Carro próprio", "Aplicativo (Uber/99)", "Transporte público",
          "Avião (atendo em outra cidade)", "Outro",
        ],
        dependeDe: { id: "p3_se_desloca", valor: "Sim" },
      },
      {
        id: "p3_custo_gasolina",
        pergunta: "Quanto você gasta com gasolina ou combustível para trabalhar por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Calcule: km percorridos por mês × consumo do carro (km/litro) × preço do litro.",
        exemplo: "500 km/mês ÷ 10 km/litro × R$ 6,50 = R$ 325/mês",
        dependeDe: { id: "p3_se_desloca", valor: "Sim" },
      },
      {
        id: "p3_custo_pedagio",
        pergunta: "Quanto você gasta com pedágio por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        dependeDe: { id: "p3_se_desloca", valor: "Sim" },
      },
      {
        id: "p3_custo_estacionamento",
        pergunta: "Quanto você gasta com estacionamento por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        dependeDe: { id: "p3_se_desloca", valor: "Sim" },
      },
      {
        id: "p3_custo_manutencao_carro",
        pergunta: "Quanto você gasta com manutenção do carro por mês? (IPVA, seguro, revisões)",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Some IPVA + seguro + revisões anuais e divida por 12 para ter o custo mensal.",
        exemplo: "IPVA R$ 2.400/ano + seguro R$ 3.600/ano + revisões R$ 1.200/ano = R$ 7.200/ano ÷ 12 = R$ 600/mês",
        dependeDe: { id: "p3_se_desloca", valor: "Sim" },
      },
      {
        id: "p3_atende_outra_cidade",
        pergunta: "Você atende em outra cidade? Precisa se hospedar?",
        tipo: "yesno",
        dependeDe: { id: "p3_se_desloca", valor: "Sim" },
      },
      {
        id: "p3_custo_viagem",
        pergunta: "Quanto você gasta com viagens para atender em outra cidade por mês?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Inclua: passagens aéreas, hospedagem, alimentação durante a viagem.",
        dependeDe: { id: "p3_atende_outra_cidade", valor: "Sim" },
      },
      {
        id: "p3_tempo_deslocamento",
        pergunta: "Quantas horas por semana você passa se deslocando para trabalhar?",
        tipo: "number",
        placeholder: "Ex: 5",
        unidade: "horas/semana",
        guia: "Inclua o tempo de ida e volta. Esse tempo tem valor — é parte do seu custo real.",
        dependeDe: { id: "p3_se_desloca", valor: "Sim" },
      },
    ],
  },
  {
    id: "faturamento_producao",
    titulo: "Faturamento e produção",
    descricao: "Agora vamos entender quanto você produz e fatura. Seja honesto — essas informações são confidenciais.",
    icone: "📊",
    perguntas: [
      {
        id: "p3_dias_trabalho",
        pergunta: "Quantos dias por semana você trabalha atendendo pacientes?",
        tipo: "number",
        placeholder: "Ex: 5",
        unidade: "dias/semana",
        obrigatoria: true,
      },
      {
        id: "p3_horas_dia",
        pergunta: "Quantas horas por dia você passa atendendo pacientes (em média)?",
        tipo: "number",
        placeholder: "Ex: 6",
        unidade: "horas/dia",
        guia: "Não conte o tempo administrativo, apenas o tempo de consultas e procedimentos.",
        obrigatoria: true,
      },
      {
        id: "p3_consultas_mes",
        pergunta: "Quantas consultas você realiza por mês em média?",
        tipo: "number",
        placeholder: "Ex: 80",
        unidade: "consultas/mês",
        obrigatoria: true,
      },
      {
        id: "p3_valor_consulta_particular",
        pergunta: "Qual é o valor da sua consulta particular?",
        tipo: "currency",
        placeholder: "0,00",
        guia: "Se você cobra valores diferentes por tipo de consulta, coloque o valor da consulta padrão.",
      },
      {
        id: "p3_valor_consulta_plano",
        pergunta: "Qual é o valor médio que você recebe por consulta pelo plano de saúde?",
        tipo: "currency",
        placeholder: "0,00",
        guia: "Verifique na tabela de repasse do plano. Se tiver vários planos, coloque a média.",
      },
      {
        id: "p3_percentual_particular",
        pergunta: "Que porcentagem das suas consultas são particulares?",
        tipo: "percentage",
        placeholder: "Ex: 30",
        guia: "Se você faz 100 consultas e 30 são particulares, coloque 30%.",
      },
      {
        id: "p3_faturamento_mensal",
        pergunta: "Qual é o seu faturamento bruto mensal aproximado? (tudo que entra antes de pagar os custos)",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Se não souber o valor exato, faça uma estimativa. Inclua consultas, procedimentos e qualquer outra receita médica.",
        obrigatoria: true,
      },
      {
        id: "p3_aceita_cartao",
        pergunta: "Você aceita pagamento por cartão de crédito ou débito?",
        tipo: "yesno",
        obrigatoria: true,
      },
      {
        id: "p3_taxa_cartao",
        pergunta: "Qual é a taxa aproximada que você paga na maquininha de cartão?",
        tipo: "percentage",
        placeholder: "Ex: 3",
        guia: "A taxa varia: débito geralmente 1,5-2%, crédito à vista 2-3%, parcelado 3-5%. Verifique no extrato da maquininha.",
        exemplo: "Se recebeu R$ 10.000 e pagou R$ 300 de taxa, sua taxa é 3%.",
        dependeDe: { id: "p3_aceita_cartao", valor: "Sim" },
      },
      {
        id: "p3_percentual_cartao",
        pergunta: "Que porcentagem dos seus recebimentos é por cartão?",
        tipo: "percentage",
        placeholder: "Ex: 60",
        guia: "Estime quanto dos seus pacientes pagam com cartão.",
        dependeDe: { id: "p3_aceita_cartao", valor: "Sim" },
      },
      {
        id: "p3_imposto_regime",
        pergunta: "Qual é o regime tributário da sua empresa médica?",
        tipo: "select",
        opcoes: [
          "Simples Nacional",
          "Lucro Presumido",
          "Lucro Real",
          "Não tenho empresa (pessoa física / autônomo)",
          "Não sei",
        ],
        guia: "Seu contador pode informar. O regime tributário afeta diretamente quanto você paga de imposto.",
      },
      {
        id: "p3_percentual_imposto",
        pergunta: "Qual é a porcentagem aproximada de impostos que você paga sobre o faturamento?",
        tipo: "percentage",
        placeholder: "Ex: 15",
        guia: "Simples Nacional: 6-15% dependendo do faturamento. Lucro Presumido: ~13-16%. Se não souber, pergunte ao seu contador.",
      },
    ],
  },
  {
    id: "ociosidade_potencial",
    titulo: "Capacidade e ociosidade",
    descricao: "Vamos descobrir quanto da sua capacidade de atendimento está sendo aproveitada.",
    icone: "📈",
    perguntas: [
      {
        id: "p3_capacidade_maxima",
        pergunta: "Qual é o número máximo de consultas que você conseguiria fazer por mês se a agenda estivesse cheia?",
        tipo: "number",
        placeholder: "Ex: 120",
        unidade: "consultas/mês",
        guia: "Calcule: dias de trabalho × consultas por dia. Ex: 20 dias × 6 consultas = 120.",
        obrigatoria: true,
      },
      {
        id: "p3_taxa_ocupacao",
        pergunta: "Hoje, que porcentagem da sua agenda está ocupada?",
        tipo: "percentage",
        placeholder: "Ex: 70",
        guia: "Se você consegue fazer 100 consultas/mês e faz 70, sua ocupação é 70%.",
        obrigatoria: true,
      },
      {
        id: "p3_motivo_ociosidade",
        pergunta: "Por que você acha que sua agenda não está 100% ocupada?",
        tipo: "multiselect",
        opcoes: [
          "Falta de pacientes novos",
          "Muitos cancelamentos",
          "Não faço marketing/divulgação",
          "Preço muito alto para minha região",
          "Concorrência forte",
          "Localização difícil",
          "Não quero mais pacientes (já estou satisfeito)",
          "Outro motivo",
        ],
        guia: "Pode marcar mais de um. Isso nos ajuda a identificar onde focar.",
      },
      {
        id: "p3_satisfeito_faturamento",
        pergunta: "Você está satisfeito com o seu faturamento atual?",
        tipo: "yesno",
      },
      {
        id: "p3_meta_faturamento",
        pergunta: "Qual seria o faturamento mensal que te deixaria satisfeito?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês",
        guia: "Seja honesto. Não precisa ser um número 'razoável' — qual é o número que realmente te satisfaria?",
      },
    ],
  },
  {
    id: "reflexao_financeira",
    titulo: "Reflexão Financeira — Aprofundamento",
    descricao: "Estas perguntas nos ajudam a entender sua relação com o dinheiro e identificar oportunidades de crescimento.",
    icone: "✨",
    perguntas: [
      {
        id: "p3_relacao_dinheiro",
        pergunta: "Como você descreveria sua relação com dinheiro? Você se sente confortável falando sobre finanças?",
        tipo: "select",
        opcoes: [
          "Muito confortável — tenho controle total das minhas finanças",
          "Razoavelmente confortável — sei o básico mas poderia melhorar",
          "Desconfortável — evito pensar nisso",
          "Muito desconfortável — finanças me causam ansiedade",
        ],
        guia: "Não há resposta certa. A relação emocional com dinheiro influencia diretamente as decisões de precificação.",
      },
      {
        id: "p3_vazamento_principal",
        pergunta: "Onde você acha que está 'vazando' dinheiro no seu negócio? O que você paga mas poderia reduzir ou eliminar?",
        tipo: "textarea",
        placeholder: "Ex: Pago por softwares que não uso, tenho muita ociosidade na agenda, desconto muito para planos...",
        guia: "Pense em gastos que você questiona quando vê no extrato. Todo negócio tem vazamentos — qual é o seu?",
      },
      {
        id: "p3_meta_financeira_real",
        pergunta: "Qual é o valor que você quer levar para casa por mês (líquido, depois de todos os custos e impostos)?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por mês líquido",
        guia: "Este é o número que realmente importa — não o faturamento bruto, mas o que sobra para você.",
        obrigatoria: true,
      },
      {
        id: "p3_maior_medo_financeiro",
        pergunta: "Qual é o seu maior medo financeiro em relação ao seu negócio médico?",
        tipo: "textarea",
        placeholder: "Ex: Perder os planos de saúde, ter que fechar a clínica, não conseguir pagar os funcionários...",
        guia: "Identificar medos financeiros é o primeiro passo para criar estratégias de proteção.",
      },
      {
        id: "p3_investimento_crescimento",
        pergunta: "Se você tivesse R$ 10.000 para investir no seu negócio agora, onde aplicaria?",
        tipo: "textarea",
        placeholder: "Ex: Em equipamentos, em marketing, em treinamento da equipe, em reformar o consultório...",
        guia: "Sua resposta revela onde você vê mais potencial de retorno no seu negócio.",
      },
    ],
  },
];

// ============================================================
// PILAR 4 — GESTÃO E PROCESSOS
// ============================================================
export const pillar4Sections: Section[] = [
  {
    id: "equipe_gestao",
    titulo: "Equipe e gestão de pessoas",
    descricao: "Como você gerencia sua equipe e os processos do dia a dia.",
    icone: "👥",
    perguntas: [
      {
        id: "p4_tem_lider_equipe",
        pergunta: "Você tem alguém que coordena sua equipe quando você não está presente?",
        tipo: "yesno",
        guia: "Pode ser uma secretária sênior, uma coordenadora, ou qualquer pessoa que tome decisões na sua ausência.",
      },
      {
        id: "p4_reuniao_equipe",
        pergunta: "Você faz reuniões regulares com sua equipe?",
        tipo: "select",
        opcoes: [
          "Sim, semanalmente",
          "Sim, mensalmente",
          "Raramente",
          "Nunca",
          "Não tenho equipe",
        ],
      },
      {
        id: "p4_manual_processos",
        pergunta: "Você tem processos documentados? (manual de como as coisas devem ser feitas)",
        tipo: "yesno",
        guia: "Processo documentado é quando você escreveu como as coisas devem ser feitas, para que qualquer pessoa possa seguir sem precisar te perguntar.",
      },
      {
        id: "p4_maior_gargalo",
        pergunta: "Qual é o maior problema ou gargalo na operação do seu consultório hoje?",
        tipo: "textarea",
        placeholder: "Ex: Muito cancelamento de última hora, secretária que não filtra bem os pacientes, demora no retorno de exames...",
        guia: "Pense no que mais te irrita ou te faz perder tempo no dia a dia.",
        obrigatoria: true,
      },
      {
        id: "p4_ausencia_2semanas",
        pergunta: "Se você ficasse 2 semanas sem trabalhar, o que aconteceria com sua clínica?",
        tipo: "select",
        opcoes: [
          "Pararia completamente — tudo depende de mim",
          "Funcionaria parcialmente — equipe gerencia o básico",
          "Funcionaria bem — tenho processos e equipe treinada",
          "Não sei o que aconteceria",
        ],
        guia: "Esta pergunta revela o quanto sua clínica depende de você pessoalmente.",
        obrigatoria: true,
      },
    ],
  },
  {
    id: "processos_atendimento",
    titulo: "Processos de atendimento",
    descricao: "Como funciona o fluxo do paciente desde o primeiro contato até o pós-consulta.",
    icone: "🔄",
    perguntas: [
      {
        id: "p4_como_paciente_chega",
        pergunta: "Como a maioria dos seus novos pacientes chega até você?",
        tipo: "multiselect",
        opcoes: [
          "Indicação de outros pacientes",
          "Indicação de outros médicos",
          "Instagram/redes sociais",
          "Google (busca orgânica)",
          "Google Ads (anúncios pagos)",
          "Plano de saúde (lista de credenciados)",
          "Hospital onde trabalho",
          "Não sei",
        ],
        obrigatoria: true,
      },
      {
        id: "p4_agendamento",
        pergunta: "Como os pacientes agendam consultas com você?",
        tipo: "multiselect",
        opcoes: [
          "Telefone", "WhatsApp", "Site próprio",
          "Aplicativo de agendamento (Doctoralia, etc.)", "Presencialmente", "Outro",
        ],
      },
      {
        id: "p4_confirmacao_consulta",
        pergunta: "Você confirma as consultas com antecedência?",
        tipo: "yesno",
        guia: "Confirmação reduz cancelamentos. Se sim, como você faz?",
      },
      {
        id: "p4_taxa_cancelamento",
        pergunta: "Qual é a taxa de cancelamento ou não comparecimento das consultas?",
        tipo: "select",
        opcoes: [
          "Menos de 5% (muito baixo)",
          "5-10% (aceitável)",
          "10-20% (preocupante)",
          "Mais de 20% (crítico)",
          "Não sei",
        ],
      },
      {
        id: "p4_retorno_paciente",
        pergunta: "Você tem um processo para trazer pacientes de volta? (retorno, acompanhamento)",
        tipo: "yesno",
        guia: "Processo de retorno é quando você tem uma rotina para lembrar pacientes de voltar — seja por WhatsApp, e-mail ou ligação.",
      },
    ],
  },
  {
    id: "reflexao_operacional",
    titulo: "Reflexão Operacional — Aprofundamento",
    descricao: "Estas perguntas nos ajudam a identificar o que pode ser melhorado na gestão do seu consultório.",
    icone: "✨",
    perguntas: [
      {
        id: "p4_horas_nao_clinicas",
        pergunta: "Quantas horas por semana você passa em atividades não clínicas? (reuniões, burocracia, e-mails, WhatsApp administrativo)",
        tipo: "number",
        placeholder: "Ex: 10",
        unidade: "horas/semana",
        guia: "Cada hora não clínica é uma hora que poderia ser usada para atender pacientes ou descansar.",
      },
      {
        id: "p4_tarefa_mais_odiada",
        pergunta: "Qual é a tarefa administrativa que você mais odeia fazer e que consome mais tempo?",
        tipo: "textarea",
        placeholder: "Ex: Responder mensagens de pacientes no WhatsApp, preencher relatórios para planos, agendar retornos...",
        guia: "Essa é provavelmente a primeira coisa que deveria ser delegada ou automatizada.",
        obrigatoria: true,
      },
      {
        id: "p4_dependencia_medico",
        pergunta: "Quais decisões na sua clínica só podem ser tomadas por você? O que sua equipe não consegue resolver sem te consultar?",
        tipo: "textarea",
        placeholder: "Ex: Qualquer dúvida de paciente, aprovação de desconto, problema com equipamento...",
        guia: "Quanto mais decisões dependem de você, menos escalável e mais estressante é o negócio.",
      },
      {
        id: "p4_processo_ideal",
        pergunta: "Se você pudesse redesenhar um processo do seu consultório do zero, qual seria e como ficaria?",
        tipo: "textarea",
        placeholder: "Ex: O agendamento — queria que fosse 100% online, com confirmação automática e sem precisar da secretária...",
        guia: "Pense no processo que mais te frustra hoje. Como seria o ideal?",
      },
      {
        id: "p4_equipe_sonho",
        pergunta: "Para ter a clínica que você quer em 3 anos, que tipo de pessoas precisaria ter na sua equipe?",
        tipo: "textarea",
        placeholder: "Ex: Uma coordenadora clínica, um profissional de marketing, um segundo médico para dividir plantões...",
        guia: "Pense nas funções, não nos nomes. Que competências estão faltando hoje?",
      },
    ],
  },
];

// ============================================================
// PILAR 5 — PRECIFICAÇÃO
// ============================================================
export const pillar5Sections: Section[] = [
  {
    id: "precificacao_atual",
    titulo: "Como você precifica hoje",
    descricao: "Vamos entender como você define os preços dos seus serviços atualmente.",
    icone: "💰",
    perguntas: [
      {
        id: "p5_como_define_preco",
        pergunta: "Como você define o preço das suas consultas e procedimentos?",
        tipo: "multiselect",
        opcoes: [
          "Baseado no que outros médicos cobram",
          "Baseado na tabela do plano de saúde",
          "Baseado no que o paciente consegue pagar",
          "Baseado nos meus custos + margem de lucro",
          "Nunca parei para calcular",
          "Outro critério",
        ],
        obrigatoria: true,
        guia: "Pode marcar mais de um. Não há resposta certa — queremos entender sua realidade.",
      },
      {
        id: "p5_ultima_vez_reajustou",
        pergunta: "Quando foi a última vez que você reajustou seus preços?",
        tipo: "select",
        opcoes: [
          "Nos últimos 6 meses",
          "Há 1 ano",
          "Há 2 anos",
          "Há mais de 2 anos",
          "Nunca reajustei",
          "Não sei",
        ],
      },
      {
        id: "p5_medo_aumentar_preco",
        pergunta: "Você tem receio de aumentar seus preços? Por quê?",
        tipo: "textarea",
        placeholder: "Ex: Tenho medo de perder pacientes, de ser julgado como ganancioso...",
        guia: "Seja honesto. Esse medo é muito comum entre médicos e é algo que trabalharemos juntos.",
      },
      {
        id: "p5_sabe_custo_hora",
        pergunta: "Você sabe quanto custa cada hora do seu tempo de trabalho?",
        tipo: "yesno",
        guia: "Custo por hora = total de custos fixos mensais ÷ horas trabalhadas por mês. Se não sabe, não se preocupe — calcularemos juntos.",
      },
      {
        id: "p5_procedimentos_lista",
        pergunta: "Liste os principais procedimentos que você realiza e o valor cobrado por cada um:",
        tipo: "textarea",
        placeholder: "Ex:\n- Consulta padrão: R$ 300\n- Retorno: R$ 200\n- Procedimento X: R$ 500\n- Procedimento Y: R$ 800",
        guia: "Não precisa ser exato. Uma estimativa já nos ajuda muito.",
        obrigatoria: true,
      },
    ],
  },
  {
    id: "custos_variaveis",
    titulo: "Custos por procedimento",
    descricao: "Além dos custos fixos, cada procedimento tem custos variáveis. Vamos identificá-los.",
    icone: "🔬",
    perguntas: [
      {
        id: "p5_material_por_consulta",
        pergunta: "Quanto você gasta em materiais por consulta padrão?",
        tipo: "currency",
        placeholder: "0,00",
        unidade: "por consulta",
        guia: "Inclua: luvas, máscara, papel da maca, materiais descartáveis usados em cada atendimento.",
        exemplo: "Luvas R$ 0,50 + máscara R$ 0,30 + papel R$ 0,20 = R$ 1,00 por consulta",
      },
      {
        id: "p5_tem_procedimento_alto_custo",
        pergunta: "Você realiza procedimentos com custo de material alto?",
        tipo: "yesno",
        guia: "Ex: cirurgias, injeções, lasers, preenchimentos, etc.",
      },
      {
        id: "p5_procedimento_alto_custo_detalhe",
        pergunta: "Qual é o custo de material do seu procedimento mais caro?",
        tipo: "textarea",
        placeholder: "Ex: Preenchimento labial: R$ 400 de material (ácido hialurônico) para cobrar R$ 1.200",
        dependeDe: { id: "p5_tem_procedimento_alto_custo", valor: "Sim" },
      },
    ],
  },
  {
    id: "reflexao_precificacao",
    titulo: "Reflexão de Precificação — Aprofundamento",
    descricao: "Estas perguntas nos ajudam a entender sua relação com precificação e identificar oportunidades de reajuste.",
    icone: "✨",
    perguntas: [
      {
        id: "p5_servico_mais_valorizado",
        pergunta: "Qual serviço ou procedimento seus pacientes mais valorizam e pelo qual eles pagariam mais sem questionar?",
        tipo: "textarea",
        placeholder: "Ex: Consultas de segunda opinião para casos complexos, procedimentos que outros médicos não fazem na cidade...",
        guia: "O serviço mais valorizado geralmente é aquele em que você tem o maior diferencial.",
        obrigatoria: true,
      },
      {
        id: "p5_crenca_limitante",
        pergunta: "Complete a frase: 'Não posso cobrar mais porque...'",
        tipo: "textarea",
        placeholder: "Ex: ...meus pacientes não têm condições, ...os outros médicos cobram menos, ...me sinto culpado...",
        guia: "Crenças limitantes sobre precificação são muito comuns entre médicos. Identificá-las é o primeiro passo para superá-las.",
        obrigatoria: true,
      },
      {
        id: "p5_comparacao_mercado",
        pergunta: "Você sabe quanto os melhores médicos da sua especialidade cobram na sua cidade?",
        tipo: "select",
        opcoes: [
          "Sim, cobro na mesma faixa",
          "Sim, cobro menos que eles",
          "Sim, cobro mais que eles",
          "Não sei quanto eles cobram",
        ],
        guia: "Conhecer o mercado é fundamental para uma precificação estratégica.",
      },
      {
        id: "p5_paciente_que_nao_questiona",
        pergunta: "Descreva o perfil do paciente que nunca questiona seu preço e volta sempre. O que ele tem em comum?",
        tipo: "textarea",
        placeholder: "Ex: São pacientes que já tentaram outros médicos sem resultado, que valorizam o tempo deles, que buscam qualidade...",
        guia: "Esses pacientes são seu mercado-alvo ideal. Entender o que eles têm em comum é ouro para o posicionamento.",
      },
      {
        id: "p5_reajuste_proximo",
        pergunta: "Se você fosse reajustar seus preços amanhã, qual seria o valor ideal e o que te impediria de fazer isso?",
        tipo: "textarea",
        placeholder: "Ex: Gostaria de cobrar R$ 500 por consulta, mas tenho medo de perder os pacientes que já tenho...",
        guia: "Esta pergunta revela tanto o potencial de receita quanto as barreiras psicológicas para crescer.",
      },
    ],
  },
];

// ============================================================
// PILAR 6 — MARKETING DIGITAL
// ============================================================
export const pillar6Sections: Section[] = [
  {
    id: "presenca_digital_atual",
    titulo: "Sua presença digital hoje",
    descricao: "Vamos entender como você está no mundo digital atualmente.",
    icone: "📱",
    perguntas: [
      {
        id: "p6_tem_instagram",
        pergunta: "Você tem perfil no Instagram?",
        tipo: "yesno",
        obrigatoria: true,
      },
      {
        id: "p6_instagram_seguidores",
        pergunta: "Quantos seguidores você tem no Instagram?",
        tipo: "number",
        placeholder: "Ex: 1200",
        dependeDe: { id: "p6_tem_instagram", valor: "Sim" },
      },
      {
        id: "p6_instagram_frequencia",
        pergunta: "Com que frequência você posta no Instagram?",
        tipo: "select",
        opcoes: [
          "Todo dia", "3-5 vezes por semana", "1-2 vezes por semana",
          "Raramente (menos de 1x por semana)", "Quase nunca",
        ],
        dependeDe: { id: "p6_tem_instagram", valor: "Sim" },
      },
      {
        id: "p6_tem_site",
        pergunta: "Você tem um site ou página profissional?",
        tipo: "yesno",
      },
      {
        id: "p6_tem_google_meu_negocio",
        pergunta: "Você tem um perfil no Google Meu Negócio? (aparece quando alguém busca seu nome no Google)",
        tipo: "yesno",
        guia: "Para verificar, busque seu nome no Google. Se aparecer um card com endereço, telefone e avaliações, você tem.",
      },
      {
        id: "p6_avaliacao_google",
        pergunta: "Qual é a sua avaliação média no Google?",
        tipo: "select",
        opcoes: [
          "5 estrelas", "4-5 estrelas", "3-4 estrelas",
          "Menos de 3 estrelas", "Não tenho avaliações", "Não sei",
        ],
        dependeDe: { id: "p6_tem_google_meu_negocio", valor: "Sim" },
      },
      {
        id: "p6_conteudo_atual",
        pergunta: "O que você costuma postar nas redes sociais?",
        tipo: "multiselect",
        opcoes: [
          "Dicas de saúde", "Casos clínicos (sem identificar paciente)",
          "Bastidores do consultório", "Conquistas e certificados",
          "Vídeos educativos", "Fotos pessoais", "Não posto nada", "Outro",
        ],
      },
    ],
  },
  {
    id: "comunicacao_tom_voz",
    titulo: "Comunicação e tom de voz",
    descricao: "Como você se comunica com seus pacientes e com o público.",
    icone: "🎙️",
    perguntas: [
      {
        id: "p6_tom_voz",
        pergunta: "Como você descreveria seu estilo de comunicação?",
        tipo: "select",
        opcoes: [
          "Formal e técnico — uso linguagem médica",
          "Acessível — explico de forma simples",
          "Próximo e empático — como um amigo que é médico",
          "Motivacional — inspiro mudanças de comportamento",
          "Ainda não tenho um estilo definido",
        ],
        obrigatoria: true,
      },
      {
        id: "p6_maior_dificuldade_marketing",
        pergunta: "Qual é sua maior dificuldade com marketing digital?",
        tipo: "multiselect",
        opcoes: [
          "Não sei o que postar", "Não tenho tempo para criar conteúdo",
          "Não me sinto à vontade na frente da câmera",
          "Não sei usar as ferramentas (Canva, CapCut, etc.)",
          "Tenho medo de ferir o Código de Ética Médica",
          "Não vejo resultado nos posts que faço",
          "Nunca tentei",
        ],
      },
      {
        id: "p6_conteudo_sonho",
        pergunta: "Se você pudesse criar qualquer tipo de conteúdo sem limitações, o que criaria?",
        tipo: "textarea",
        placeholder: "Ex: Vídeos explicando doenças de forma simples, lives respondendo dúvidas, séries sobre prevenção...",
        guia: "Pense no conteúdo que você gostaria de consumir se fosse paciente da sua especialidade.",
      },
    ],
  },
  {
    id: "reflexao_marketing",
    titulo: "Reflexão de Marketing — Aprofundamento",
    descricao: "Estas perguntas nos ajudam a construir uma estratégia de marketing autêntica e eficaz para você.",
    icone: "✨",
    perguntas: [
      {
        id: "p6_conteudo_que_funciona",
        pergunta: "Algum post, vídeo ou conteúdo que você publicou gerou muita resposta positiva? O que era?",
        tipo: "textarea",
        placeholder: "Ex: Um vídeo explicando sobre hipertensão teve 10x mais visualizações que o normal...",
        guia: "O que já funcionou é o melhor indicador do que vai funcionar de novo.",
      },
      {
        id: "p6_paciente_veio_redes",
        pergunta: "Você já teve paciente que veio especificamente por causa de algo que você postou nas redes sociais?",
        tipo: "yesno",
        guia: "Mesmo um único caso já prova que o marketing digital funciona para você.",
      },
      {
        id: "p6_historia_que_contaria",
        pergunta: "Qual história da sua prática médica você acha que mais impactaria e educaria seus pacientes ideais?",
        tipo: "textarea",
        placeholder: "Ex: A história de um paciente que chegou desesperado e como o diagnóstico correto mudou tudo...",
        guia: "Histórias reais (sem identificar pacientes) são o conteúdo mais poderoso que um médico pode criar.",
        obrigatoria: true,
      },
      {
        id: "p6_tempo_disponivel_marketing",
        pergunta: "Quantas horas por semana você conseguiria dedicar à criação de conteúdo?",
        tipo: "select",
        opcoes: [
          "Menos de 1 hora",
          "1-2 horas",
          "3-5 horas",
          "Mais de 5 horas",
          "Prefiro delegar tudo",
        ],
        guia: "Realismo é fundamental. Uma estratégia de marketing que você consegue manter é melhor que uma perfeita que você abandona.",
      },
      {
        id: "p6_tom_voz_ideal",
        pergunta: "Como você quer que seus pacientes se sintam ao ver seu conteúdo? Que emoção ou sensação você quer transmitir?",
        tipo: "textarea",
        placeholder: "Ex: Quero que se sintam seguros, que confiem em mim antes mesmo de me conhecer pessoalmente...",
        guia: "O tom de voz ideal é aquele que atrai exatamente o paciente que você quer atender.",
        obrigatoria: true,
      },
    ],
  },
];

// ============================================================
// PILAR 7 — VENDAS E COMUNICAÇÃO
// ============================================================
export const pillar7Sections: Section[] = [
  {
    id: "apresentacao_tratamento",
    titulo: "Como você apresenta tratamentos",
    descricao: "A forma como você apresenta um tratamento influencia diretamente se o paciente aceita ou não.",
    icone: "🤝",
    perguntas: [
      {
        id: "p7_como_apresenta",
        pergunta: "Como você costuma apresentar um plano de tratamento para o paciente?",
        tipo: "textarea",
        placeholder: "Descreva como é sua consulta quando você precisa propor um tratamento...",
        guia: "Pense em uma consulta típica onde você propõe um tratamento ou procedimento.",
        obrigatoria: true,
      },
      {
        id: "p7_explica_valor",
        pergunta: "Você costuma explicar o valor (benefício) do tratamento antes de falar o preço?",
        tipo: "yesno",
        guia: "Valor aqui significa o benefício para o paciente — o que ele vai ganhar com o tratamento.",
      },
      {
        id: "p7_taxa_aceitacao",
        pergunta: "Quando você propõe um tratamento, qual é a porcentagem de pacientes que aceita?",
        tipo: "select",
        opcoes: [
          "Mais de 80% aceitam",
          "60-80% aceitam",
          "40-60% aceitam",
          "Menos de 40% aceitam",
          "Não sei",
        ],
        obrigatoria: true,
      },
    ],
  },
  {
    id: "objecoes_comuns",
    titulo: "Objeções mais comuns",
    descricao: "Objeções são as razões que os pacientes dão para não aceitar o tratamento. Vamos identificá-las.",
    icone: "🛡️",
    perguntas: [
      {
        id: "p7_objecoes",
        pergunta: "Quais são as objeções mais comuns que você ouve dos pacientes?",
        tipo: "multiselect",
        opcoes: [
          "\"Está muito caro\"",
          "\"Vou pensar e te aviso\"",
          "\"Preciso consultar meu marido/esposa\"",
          "\"Tenho medo do procedimento\"",
          "\"Vou pesquisar mais antes de decidir\"",
          "\"Não tenho tempo agora\"",
          "\"Meu plano não cobre\"",
          "\"Já fiz isso antes e não funcionou\"",
        ],
        obrigatoria: true,
      },
      {
        id: "p7_como_responde_objecao",
        pergunta: "Como você costuma responder quando um paciente diz que está caro?",
        tipo: "textarea",
        placeholder: "Descreva como você reage e o que costuma dizer...",
        guia: "Não existe resposta certa. Queremos entender seu estilo atual para melhorá-lo.",
        obrigatoria: true,
      },
      {
        id: "p7_perde_paciente_preco",
        pergunta: "Você acredita que perde pacientes por causa do preço?",
        tipo: "yesno",
      },
      {
        id: "p7_diferencia_valor_preco",
        pergunta: "Você consegue explicar a diferença entre o preço e o valor do seu serviço para o paciente?",
        tipo: "yesno",
        guia: "Preço é o que o paciente paga. Valor é o que ele recebe em troca. Um bom médico consegue mostrar que o valor é maior que o preço.",
      },
    ],
  },
  {
    id: "reflexao_conversao",
    titulo: "Reflexão de Conversão — Aprofundamento",
    descricao: "Estas perguntas nos ajudam a construir um processo de comunicação ética e eficaz com seus pacientes.",
    icone: "✨",
    perguntas: [
      {
        id: "p7_consulta_ideal",
        pergunta: "Descreva como seria sua consulta ideal — do momento em que o paciente entra até sair. O que aconteceria?",
        tipo: "textarea",
        placeholder: "Ex: O paciente chegaria já com os exames organizados, eu teria 45 min para ouvir e examinar, apresentaria o plano com calma...",
        guia: "A consulta ideal revela o que você valoriza e o que está faltando no processo atual.",
        obrigatoria: true,
      },
      {
        id: "p7_paciente_que_mais_converte",
        pergunta: "Qual tipo de paciente aceita seu tratamento mais facilmente? O que ele tem em comum?",
        tipo: "textarea",
        placeholder: "Ex: Pacientes que vieram por indicação de outros pacientes, que já pesquisaram sobre o tratamento antes...",
        guia: "Entender quem converte melhor ajuda a atrair mais desse perfil.",
      },
      {
        id: "p7_momento_decisao",
        pergunta: "Em que momento da consulta o paciente geralmente decide se vai ou não aceitar o tratamento?",
        tipo: "select",
        opcoes: [
          "Quando eu apresento o diagnóstico",
          "Quando eu explico o tratamento",
          "Quando eu falo o preço",
          "Depois que sai da consulta (decide em casa)",
          "Varia muito — não tenho padrão",
        ],
        guia: "Identificar o momento de decisão permite trabalhar melhor aquele ponto específico.",
      },
      {
        id: "p7_followup_atual",
        pergunta: "Você tem algum processo de acompanhamento após a consulta? (ligação, WhatsApp, e-mail)",
        tipo: "textarea",
        placeholder: "Ex: Minha secretária liga 3 dias depois para saber como o paciente está...",
        guia: "Follow-up bem feito aumenta a taxa de retorno e de indicações.",
      },
      {
        id: "p7_script_sonho",
        pergunta: "Se você pudesse ter um script perfeito para apresentar seu tratamento mais importante, o que ele diria?",
        tipo: "textarea",
        placeholder: "Ex: Começaria explicando o problema em linguagem simples, depois mostraria o impacto na vida, depois apresentaria a solução...",
        guia: "Não precisa ser o script final — é um ponto de partida que o mentor vai refinar com você.",
        obrigatoria: true,
      },
    ],
  },
];

// ============================================================
// MAPA DE PILARES
// ============================================================
export const PILLAR_SECTIONS: Record<number, Section[]> = {
  1: pillar1Sections,
  2: pillar2Sections,
  3: pillar3Sections,
  4: pillar4Sections,
  5: pillar5Sections,
  6: pillar6Sections,
  7: pillar7Sections,
};

export const PILLAR_TITLES: Record<number, string> = {
  1: "Identidade e Propósito",
  2: "Posicionamento",
  3: "Diagnóstico do Negócio",
  4: "Gestão e Processos",
  5: "Precificação",
  6: "Marketing Digital",
  7: "Vendas e Comunicação",
};

export const PILLAR_ICONS: Record<number, string> = {
  1: "🎯", 2: "📌", 3: "📊", 4: "⚙️", 5: "💰", 6: "📱", 7: "🤝",
};
