export const PILLARS = [
  {
    id: 1,
    title: "Mapa Estratégico",
    short: "Mapa",
    color: "bg-blue-900",
    textColor: "text-blue-900",
    lightBg: "bg-blue-50",
    borderColor: "border-blue-200",
    emoji: "🎯",
    checklist: [
      "Definiu seu propósito profissional",
      "Identificou seus valores inegociáveis",
      "Completou o Ikigai profissional",
      "Criou missão e visão",
      "Definiu público-alvo e nicho",
      "Elaborou posicionamento de mercado",
    ],
  },
  {
    id: 2,
    title: "Produto Profissional",
    short: "Produto",
    color: "bg-indigo-900",
    textColor: "text-indigo-900",
    lightBg: "bg-indigo-50",
    borderColor: "border-indigo-200",
    emoji: "💡",
    checklist: [
      "Definiu seu diferencial competitivo",
      "Criou proposta de valor clara",
      "Listou serviços e subprodutos possíveis",
      "Identificou oportunidades de receita alternativa",
    ],
  },
  {
    id: 3,
    title: "Diagnóstico",
    short: "Diagnóstico",
    color: "bg-slate-800",
    textColor: "text-slate-800",
    lightBg: "bg-slate-50",
    borderColor: "border-slate-200",
    emoji: "📊",
    checklist: [
      "Mapeou todas as despesas fixas",
      "Preencheu o iVMP completo",
      "Analisou custos ocultos",
      "Calculou custo por hora real",
      "Entendeu precificação atual",
    ],
  },
  {
    id: 4,
    title: "Estratégia",
    short: "Estratégia",
    color: "bg-amber-800",
    textColor: "text-amber-800",
    lightBg: "bg-amber-50",
    borderColor: "border-amber-200",
    emoji: "🗺️",
    checklist: [
      "Simulou cenários financeiros",
      "Definiu tabela de preços ideal",
      "Traçou plano de ação com prioridades",
      "Definiu timeline de implementação",
    ],
  },
  {
    id: 5,
    title: "Comunicação",
    short: "Comunicação",
    color: "bg-teal-800",
    textColor: "text-teal-800",
    lightBg: "bg-teal-50",
    borderColor: "border-teal-200",
    emoji: "📱",
    checklist: [
      "Avaliou presença digital atual",
      "Definiu estratégia de conteúdo",
      "Gerou prompt master de comunicação",
      "Criou calendário editorial",
    ],
  },
  {
    id: 6,
    title: "Vendas",
    short: "Vendas",
    color: "bg-rose-900",
    textColor: "text-rose-900",
    lightBg: "bg-rose-50",
    borderColor: "border-rose-200",
    emoji: "🤝",
    checklist: [
      "Criou protocolo de consulta personalizado",
      "Aprendeu técnicas de apresentação de valor",
      "Definiu tratamento de objeções",
      "Implementou sistema de follow-up",
    ],
  },
];

export const PILLAR_COLORS = [
  { bg: "bg-blue-900", text: "text-white", light: "bg-blue-50", border: "border-blue-200" },
  { bg: "bg-indigo-900", text: "text-white", light: "bg-indigo-50", border: "border-indigo-200" },
  { bg: "bg-slate-800", text: "text-white", light: "bg-slate-50", border: "border-slate-200" },
  { bg: "bg-amber-800", text: "text-white", light: "bg-amber-50", border: "border-amber-200" },
  { bg: "bg-teal-800", text: "text-white", light: "bg-teal-50", border: "border-teal-200" },
  { bg: "bg-rose-900", text: "text-white", light: "bg-rose-50", border: "border-rose-200" },
];
